name: terrarium4u
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76222
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c9dbeb'
    - '#706459'
    - '#0e151a'
    - '#4a3e3b'
    - '#a9ac9d'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
